### ISSUE TITLE
Op Support: aten.nll_loss_forward.default

### ISSUE THREAD

**Issue by shivadbhavsar** [ROCm/torch_migraphx#94]
Add aten converter.
Affected models:
Huggingface: DebertaV2ForMaskedLM, MT5ForConditionalGeneration, DebertaV2ForQuestionAnswering, AllenaiLongformerBase

**Comment by bpickrel** [comment]
Coming up to speed:

- Familiarization with Pytorch
- Familiarization with `pytest` test framework
- Familiarization with `torch-migraphx` converters
- Familiarization with Pytorch `NLLLoss` function and mathematical implementation
-  - Includes a selection process equivalent to the Onnx `GatherElements` op.

Coding:

- Add a new converter (Python language) for acc_ops to `acc_ops_converters.py` where the main logic goes
- Add a converter for ATen ops to `aten_ops_converters.py` as a wrapper for the acc_ops converter 
- Add pytest test in `test_activations_fx.py`
- Add pytest test in `test_activations_dynamo.py` 
- To speed up more detailed test/dev work, write a Python script that imports migraphx and makes Migraphx API calls such as `add_instruction` directly and runs a program with 2-3 instructions.  This allows viewing inputs and intermediate values directly while I'm coding, without pytest overhead.
- Code an implementation of `NLLLoss` with Migraphx Python API.
- Implentation will include the equivalent of  Onnx `GatherElements` , using Migraphx Python API, as one step.  Migraphx doesn't have such an op. in either C++ or Python, but the Onnx parsers (C++) contain an implementation using existing Migraphx ops including `Gather` and others, for use as a guide.
- **Variations to be supported:**  `NLLLoss` has 5 optional parameters of which 2 are deprecated, but all options for the other 3 must be supported.  In addition, 2 required inputs must support two possible formats for either 2 dimensions or k-dimension. 
- **Extra:**  Add the new `GatherElements` code to the Migraphx Python codebase as a new method.  This should be little additional work, but could be put off to a separate PR if it proves to be a big job.

**Comment by bpickrel** [comment]
Current status:  Have 1 pytest test in place (the other is just a wrapper) and two converters in place.  These tests run end-to-end (showing all required components are in place) but still give wrong results because the internal converter code contains placeholders.  Coding of converter is in progress; now working on the `GatherElements` portion which is the trickiest.  I got it working for the 1-dimensional case; now extending it to k-dimensions.

**Comment by bpickrel** [comment]
Confirmed that none of the NLL_Loss ops in the above listed models uses an input with more than 2 dimensions, so k-dims input support is not necessary to this PR.

**Comment by bpickrel** [comment]
The second converter test (aten/dynamo) fails because there's a more significant difference between the `ATen` and `acc` converters for this operation:  the `ATen` version has a different return type with 2 values instead of 1.  Must add more housekeeping to the code to accommodate this.  Don't think we need to add code to use the second return value.
